### PR TITLE
mapy.cz photo, base, touristic layer

### PR DESCRIPTION
**Pull request by frettie**
Hi Simon!
There is czech mapy.cz mapservice layers with 
- photo map (over all world by bing maps and T-maps - CZ republic ) 
- touristic map (better map to country, all over the world)
- base map (czech classic map - all over the world)

i test it at localhost (where i have some problems with your package.json, i have to edit ui-router to new version, but is ok) and maps are ok. 

Thank you for check it.
J.

### CODE REVIEW

**Comment by frettie** [comment]
@simon04 what next with this branch? :)

**Comment by simon04** [comment]
Hi @frettie, sorry for the long delay. I've been quite inactive on GitHub recently. In the long run, I'd like to head for #28. In the meanwhile, I'm happy to merge this PR, once the following questions are resolved:
* which attribution is necessary? Do we need to mention seznam.cz, or mapy.cz?
* is it okay to use the mapy.cz tiles for the locator-tool?

Thanks!

**Comment by frettie** [comment]
Hello, thanks for reaction!

1) i think, that is not need, to attribute mapy.cz, but screenshots and other materials from mapy.cz are on CC-BY-SA 4.0 - and mapy.cz use data from OSM. So it is ok without attribution.
2) Hello, yes, it is possible, we can use screenshots to wikipedia directly. https://cs.wikipedia.org/wiki/Wikipedie:Vyu%C5%BEit%C3%AD_mapov%C3%BDch_podklad%C5%AF_z_Mapy.cz

Thanks!

**Comment by simon04** [comment]
Thanks for the clarification. I merged this PR and deployed the new version.

**Pull request merged**
